### ISSUE TITLE
On FreeBSD 10.0-RELEASE-p2, Riak 2.0 Solr temp directory missing

### ISSUE THREAD

**Issue by themartorana** [basho/node_package#138]
@cheeseplus mentioned this might be a configuration issue, so I'm posting this here.

After installing the Riak 2.0 package and starting the Riak service, Riak crashed because Solr fails to start properly. The Solr log file shows a missing temp directory:

crash.log:

```
2014-04-30 18:53:22 =ERROR REPORT====
** Generic server yz_solr_proc terminating
** Last message in was {#Port<0.10846>,{exit_status,1}}
** When Server state == {state,"/data/riak/yz",#Port<0.10846>,8093,8985}
** Reason for termination ==
** {"solr OS process exited",1}
2014-04-30 18:53:22 =CRASH REPORT====
  crasher:
    initial call: yz_solr_proc:init/1
    pid: <0.6722.0>
    registered_name: yz_solr_proc
    exception exit: {{"solr OS process exited",1},[{gen_server,terminate,6,[{file,"gen_server.erl"},{line,744}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,239}]}]}
    ancestors: [yz_solr_sup,yz_sup,<0.916.0>]
    messages: [{'EXIT',#Port<0.10846>,normal}]
    links: [<0.918.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 610
    stack_size: 27
    reductions: 7736
  neighbours:
2014-04-30 18:53:22 =SUPERVISOR REPORT====
     Supervisor: {local,yz_solr_sup}
     Context:    child_terminated
     Reason:     {"solr OS process exited",1}
     Offender:   [{pid,<0.6722.0>},{name,yz_solr_proc},{mfargs,{yz_solr_proc,start_link,["/data/riak/yz",8093,8985]}},{restart_type,permanent},{shutdown,5000},{child_type,worker}]

2014-04-30 18:53:22 =SUPERVISOR REPORT====
     Supervisor: {local,yz_solr_sup}
     Context:    shutdown
     Reason:     reached_max_restart_intensity
     Offender:   [{pid,<0.6722.0>},{name,yz_solr_proc},{mfargs,{yz_solr_proc,start_link,["/data/riak/yz",8093,8985]}},{restart_type,permanent},{shutdown,5000},{child_type,worker}]

2014-04-30 18:53:22 =SUPERVISOR REPORT====
     Supervisor: {local,yz_sup}
     Context:    child_terminated
     Reason:     shutdown
     Offender:   [{pid,<0.918.0>},{name,yz_solr_sup},{mfargs,{yz_solr_sup,start_link,[]}},{restart_type,permanent},{shutdown,5000},{child_type,supervisor}]

2014-04-30 18:53:22 =SUPERVISOR REPORT====
     Supervisor: {local,yz_sup}
     Context:    shutdown
     Reason:     reached_max_restart_intensity
     Offender:   [{pid,<0.918.0>},{name,yz_solr_sup},{mfargs,{yz_solr_sup,start_link,[]}},{restart_type,permanent},{shutdown,5000},{child_type,supervisor}]
```

solr.log:

```
2014-04-30 18:52:52,474 [WARN] <main>@XmlConfiguration.java:404 Config error at <Set name="tempDirectory"><Property name="jetty.home" default="."/>/solr-webapp</Set>
2014-04-30 18:52:52,478 [WARN] <main>@DeploymentManager.java:501 Unable to reach node goal: started
java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.set(XmlConfiguration.java:561)
    at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.configure(XmlConfiguration.java:384)
    at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.configure(XmlConfiguration.java:343)
    at org.eclipse.jetty.xml.XmlConfiguration.configure(XmlConfiguration.java:296)
    at org.eclipse.jetty.deploy.providers.ContextProvider.createContextHandler(ContextProvider.java:87)
    at org.eclipse.jetty.deploy.App.getContextHandler(App.java:100)
    at org.eclipse.jetty.deploy.bindings.StandardDeployer.processBinding(StandardDeployer.java:36)
    at org.eclipse.jetty.deploy.AppLifeCycle.runBindings(AppLifeCycle.java:186)
    at org.eclipse.jetty.deploy.DeploymentManager.requestAppGoal(DeploymentManager.java:494)
    at org.eclipse.jetty.deploy.DeploymentManager.addApp(DeploymentManager.java:141)
    at org.eclipse.jetty.deploy.providers.ScanningAppProvider.fileAdded(ScanningAppProvider.java:145)
    at org.eclipse.jetty.deploy.providers.ScanningAppProvider$1.fileAdded(ScanningAppProvider.java:56)
    at org.eclipse.jetty.util.Scanner.reportAddition(Scanner.java:609)
    at org.eclipse.jetty.util.Scanner.reportDifferences(Scanner.java:540)
    at org.eclipse.jetty.util.Scanner.scan(Scanner.java:403)
    at org.eclipse.jetty.util.Scanner.doStart(Scanner.java:337)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
    at org.eclipse.jetty.deploy.providers.ScanningAppProvider.doStart(ScanningAppProvider.java:121)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
    at org.eclipse.jetty.deploy.DeploymentManager.startAppProvider(DeploymentManager.java:555)
    at org.eclipse.jetty.deploy.DeploymentManager.doStart(DeploymentManager.java:230)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
    at org.eclipse.jetty.util.component.AggregateLifeCycle.doStart(AggregateLifeCycle.java:81)
    at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:58)
    at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:96)
    at org.eclipse.jetty.server.Server.doStart(Server.java:280)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
    at org.eclipse.jetty.xml.XmlConfiguration$1.run(XmlConfiguration.java:1259)
    at java.security.AccessController.doPrivileged(Native Method)
    at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1182)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at org.eclipse.jetty.start.Main.invokeMain(Main.java:473)
    at org.eclipse.jetty.start.Main.start(Main.java:615)
    at org.eclipse.jetty.start.Main.main(Main.java:96)
Caused by: java.lang.IllegalArgumentException: Bad temp directory: /usr/local/lib/riak/solr-webapp
    at org.eclipse.jetty.webapp.WebAppContext.setTempDirectory(WebAppContext.java:1129)
    ... 41 more
```

Adding `/usr/local/lib/riak/solr-webapp` and setting the appropriate permissions on the directory, everything runs smoothly.

Cheers,

Dave

**Comment by jaredmorrow** [comment]
@rzezeski did you get a chance to look at this?

**Comment by rzezeski** [comment]
@themartorana I'm closing this as the bug is being tracked by basho/yokozuna#387.

**Comment by jaredmorrow** [comment]
Thanks Z!

**Comment by themartorana** [comment]
Thanks, @rzezeski
